apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      values: |
        global:
          meshID: home-mesh
          multiCluster:
            clusterName: Cluster-Proxy
          network: home-network
            |
      releaseName: istiod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  values:
    global:
      meshID: home-mesh
      multiCluster:
        clusterName: cluster-main
      network: home-network
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
