apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      values: |
        service:
          type: LoadBalancer
          ports:
            - name: tls-istiod
              port: 15012
              targetPort: 15012
            - name: tls-mesh
              port: 15443
              targetPort: 15443
      releaseName: istio-gateway
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
